### ISSUE TITLE
Warning from: use double

### ISSUE THREAD

**Issue by nilslice** [ircmaxell/FFIMe#19]
Hey there - is there a way to disable the `use double` statement from being generated in the FFI wrapper?

See this issue here for reference:

https://github.com/extism/extism/issues/142

Forgive my naivety, but I'm not sure what that statement does, but it consistently produces a warning printed to output.

**Comment by ircmaxell** [comment]
@bwoebi  can you remember why this was added? https://github.com/ircmaxell/FFIMe/commit/d6292e8d1cfe7b5c8fd902bda42dcbc4bf19fd70

**Comment by bwoebi** [comment]
@ircmaxell It's because of this warning: https://github.com/php/php-src/blob/77ee92a50cee4ea6f9ae1994ea7950b110e4496e/Zend/zend_compile.c#L6338-L6355

**Comment by ircmaxell** [comment]
But it seems to be causing a warning, no?

**Comment by bwoebi** [comment]
Looks like the `use double;` shall not be used if no namespace is given. Let's remove it then.

**Comment by nilslice** [comment]
Thanks!
