### ISSUE TITLE
Missing int_ptr classes

### ISSUE THREAD

**Issue by jgmdev** [ircmaxell/FFIMe#4]
I'm playing around with [IUP](https://www.tecgraf.puc-rio.br/iup/) (a gui toolkit written in C which seems a nice test case for this generator) and the library uses references to integers, below code is needed [here](https://github.com/ircmaxell/FFIMe/blob/master/lib/Compiler.php#L55):

```php
$class = array_merge($class, $this->compileDeclClassImpl('int_ptr', 'int*', $className));
$class = array_merge($class, $this->compileDeclClassImpl('int_ptr_ptr', 'int**', $className));
$class = array_merge($class, $this->compileDeclClassImpl('int_ptr_ptr_ptr', 'int***', $className));
```

**Comment by ircmaxell** [comment]
Thanks for the report!

I'll get a fix pushed out in the next few days (should be easy, but will do when I get to a computer)...
