### ISSUE TITLE
 Uncaught LogicException: Could not find header file: errno.h given context

### ISSUE THREAD

**Issue by stayeronglass** [ircmaxell/FFIMe#8]
```
<?php
error_reporting(-1);



require __DIR__ . '/vendor/autoload.php';



(new FFIMe\FFIMe("/usr/lib/x86_64-linux-gnu/libuv.so"))
    ->include('/usr/include/uv.h')
    ->codeGen('/libuv.php');
```

```

array(4) {
  [0]=>
  string(18) "/usr/local/include"
  [1]=>
  string(12) "/usr/include"
  [2]=>
  string(29) "/usr/include/x86_64-linux-gnu"
  [3]=>
  string(39) "/usr/lib/gcc/x86_64-linux-gnu/8/include"
}
PHP Fatal error:  Uncaught LogicException: Could not find header file: errno.h given context /usr/include (called from /usr/include/uv-errno.h) in /home/projects/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php:251
Stack trace:
#0 /home/projects/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(189): PHPCParser\PreProcessor->findHeaderFile()
#1 /home/projects/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(221): PHPCParser\PreProcessor->findAndParse()
#2 /home/projects/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(50): PHPCParser\PreProcessor->resolveInclude()
#3 /home/projects/vendor/ircmaxell/php-c-parser/lib/CParser.php(22): PHPCParser\PreProcessor->process()
#4 /home/projects/vendor/ircmaxell/ffime/lib/FFIMe.php(101): PHPCParser\CParser->parse()
#5 /home/projects/test.php(11): FFIMe\FFIMe->include()
#6 {main}
  thrown in /home/projects/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php on line 251
```

**Comment by stayeronglass** [comment]
```
/home/projects # uname -a
Linux Ubuntu-1804-bionic-64-minimal 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ircmaxell** [comment]
Can you try running `ls -d /usr/lib/gcc/x86_64-linux-gnu/*/*/` and output the result here?

**Comment by stayeronglass** [comment]
ls: cannot access '/usr/lib/gcc/x86_64-linux-gnu/*/*/': No such file or director                                                                                                                                                             y

/usr/lib/gcc/x86_64-linux-gnu # ls
8

 /usr/lib/gcc/x86_64-linux-gnu/8 # ls -d
.

 # find -iname errno.h
./usr/src/linux-headers-4.15.0-58/include/uapi/asm-generic/errno.h
./usr/src/linux-headers-4.15.0-58/include/uapi/linux/errno.h
./usr/src/linux-headers-4.15.0-58/include/linux/errno.h
./usr/src/linux-headers-4.15.0-58/arch/parisc/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/score/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/powerpc/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/frv/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/m32r/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/ia64/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/alpha/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/x86/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/mips/include/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/mips/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/mn10300/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-58/arch/sparc/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/include/uapi/asm-generic/errno.h
./usr/src/linux-headers-4.15.0-62/include/uapi/linux/errno.h
./usr/src/linux-headers-4.15.0-62/include/linux/errno.h
./usr/src/linux-headers-4.15.0-62/arch/parisc/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/score/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/powerpc/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/frv/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/m32r/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/ia64/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/alpha/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/x86/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/mips/include/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/mips/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/mn10300/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-62/arch/sparc/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/include/uapi/asm-generic/errno.h
./usr/src/linux-headers-4.15.0-64/include/uapi/linux/errno.h
./usr/src/linux-headers-4.15.0-64/include/linux/errno.h
./usr/src/linux-headers-4.15.0-64/arch/parisc/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/score/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/powerpc/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/frv/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/m32r/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/ia64/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/alpha/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/x86/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/mips/include/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/mips/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/mn10300/include/uapi/asm/errno.h
./usr/src/linux-headers-4.15.0-64/arch/sparc/include/uapi/asm/errno.h

**Comment by stayeronglass** [comment]
/usr/lib/gcc/x86_64-linux-gnu/8 is empty

**Comment by ircmaxell** [comment]
Stupid question: do you have GCC installed?

```
sudo apt-get install build-essential
```

**Comment by stayeronglass** [comment]
um, no. please provide full requirements in readme.

**Comment by ircmaxell** [comment]
I wasn't even aware it was a requirement.

Happy to add it though. Any chance you could pull together a pull request to add it in?

**Comment by stayeronglass** [comment]
i'll try.

now i got an error

PHP Fatal error:  Uncaught LogicException: Syntax Error: expecting ": EXPR" in ternary expression in /home/projects/vendor/ircmaxell/php-c-parser/lib/Context.php:309
Stack trace:
#0 /home/projects/vendor/ircmaxell/php-c-parser/lib/Context.php(146): PHPCParser\Context->evaluateInternal()
#1 /home/projects/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(132): PHPCParser\Context->evaluate()
#2 /home/projects/vendor/ircmaxell/php-c-parser/lib/PreProcessor.php(81): PHPCParser\PreProcessor->evaluateIf()
#3 /home/projects/vendor/ircmaxell/php-c-parser/lib/CParser.php(22): PHPCParser\PreProcessor->process()
#4 /home/projects/vendor/ircmaxell/ffime/lib/FFIMe.php(101): PHPCParser\CParser->parse()
#5 /home/projects/test.php(11): FFIMe\FFIMe->include()
#6 {main}
  thrown in /home/projects/vendor/ircmaxell/php-c-parser/lib/Context.php on line 309

**Comment by ircmaxell** [comment]
That's currently a known issue: https://github.com/ircmaxell/php-c-parser/issues/6

**Comment by bwoebi** [comment]
The parent known issue has been fixed. Closing this.
